// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/course.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoursesClient is the client API for Courses service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoursesClient interface {
	// For users
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Unenroll(ctx context.Context, in *UnenrollRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetEnrolledCoursesForUser(ctx context.Context, in *GetEnrolledCoursesForUserRequest, opts ...grpc.CallOption) (*GetEnrolledCoursesForUserResponse, error)
	// For teachers
	CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error)
	// For course
	GetCourseToC(ctx context.Context, in *GetCourseToCRequest, opts ...grpc.CallOption) (*GetCourseToCResponse, error)
	GetCourseSummary(ctx context.Context, in *GetCourseSummaryRequest, opts ...grpc.CallOption) (*GetCourseSummaryResponse, error)
	GetCourseDashboard(ctx context.Context, in *GetCourseDashboardRequest, opts ...grpc.CallOption) (*GetCourseDashboardResponse, error)
	GetAllPublicCourses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllPublicCoursesResponse, error)
	// For page
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error)
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type coursesClient struct {
	cc grpc.ClientConnInterface
}

func NewCoursesClient(cc grpc.ClientConnInterface) CoursesClient {
	return &coursesClient{cc}
}

func (c *coursesClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/Enroll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) Unenroll(ctx context.Context, in *UnenrollRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/Unenroll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) GetEnrolledCoursesForUser(ctx context.Context, in *GetEnrolledCoursesForUserRequest, opts ...grpc.CallOption) (*GetEnrolledCoursesForUserResponse, error) {
	out := new(GetEnrolledCoursesForUserResponse)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/GetEnrolledCoursesForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error) {
	out := new(CreateCourseResponse)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/CreateCourse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) GetCourseToC(ctx context.Context, in *GetCourseToCRequest, opts ...grpc.CallOption) (*GetCourseToCResponse, error) {
	out := new(GetCourseToCResponse)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/GetCourseToC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) GetCourseSummary(ctx context.Context, in *GetCourseSummaryRequest, opts ...grpc.CallOption) (*GetCourseSummaryResponse, error) {
	out := new(GetCourseSummaryResponse)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/GetCourseSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) GetCourseDashboard(ctx context.Context, in *GetCourseDashboardRequest, opts ...grpc.CallOption) (*GetCourseDashboardResponse, error) {
	out := new(GetCourseDashboardResponse)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/GetCourseDashboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) GetAllPublicCourses(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAllPublicCoursesResponse, error) {
	out := new(GetAllPublicCoursesResponse)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/GetAllPublicCourses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error) {
	out := new(GetPageResponse)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/CreatePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coursesClient) DeletePage(ctx context.Context, in *DeletePageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/scholarlabs.services.course.Courses/DeletePage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoursesServer is the server API for Courses service.
// All implementations must embed UnimplementedCoursesServer
// for forward compatibility
type CoursesServer interface {
	// For users
	Enroll(context.Context, *EnrollRequest) (*emptypb.Empty, error)
	Unenroll(context.Context, *UnenrollRequest) (*emptypb.Empty, error)
	GetEnrolledCoursesForUser(context.Context, *GetEnrolledCoursesForUserRequest) (*GetEnrolledCoursesForUserResponse, error)
	// For teachers
	CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error)
	// For course
	GetCourseToC(context.Context, *GetCourseToCRequest) (*GetCourseToCResponse, error)
	GetCourseSummary(context.Context, *GetCourseSummaryRequest) (*GetCourseSummaryResponse, error)
	GetCourseDashboard(context.Context, *GetCourseDashboardRequest) (*GetCourseDashboardResponse, error)
	GetAllPublicCourses(context.Context, *emptypb.Empty) (*GetAllPublicCoursesResponse, error)
	// For page
	GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error)
	CreatePage(context.Context, *CreatePageRequest) (*emptypb.Empty, error)
	DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCoursesServer()
}

// UnimplementedCoursesServer must be embedded to have forward compatible implementations.
type UnimplementedCoursesServer struct {
}

func (UnimplementedCoursesServer) Enroll(context.Context, *EnrollRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedCoursesServer) Unenroll(context.Context, *UnenrollRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unenroll not implemented")
}
func (UnimplementedCoursesServer) GetEnrolledCoursesForUser(context.Context, *GetEnrolledCoursesForUserRequest) (*GetEnrolledCoursesForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrolledCoursesForUser not implemented")
}
func (UnimplementedCoursesServer) CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedCoursesServer) GetCourseToC(context.Context, *GetCourseToCRequest) (*GetCourseToCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseToC not implemented")
}
func (UnimplementedCoursesServer) GetCourseSummary(context.Context, *GetCourseSummaryRequest) (*GetCourseSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseSummary not implemented")
}
func (UnimplementedCoursesServer) GetCourseDashboard(context.Context, *GetCourseDashboardRequest) (*GetCourseDashboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseDashboard not implemented")
}
func (UnimplementedCoursesServer) GetAllPublicCourses(context.Context, *emptypb.Empty) (*GetAllPublicCoursesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPublicCourses not implemented")
}
func (UnimplementedCoursesServer) GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedCoursesServer) CreatePage(context.Context, *CreatePageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedCoursesServer) DeletePage(context.Context, *DeletePageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePage not implemented")
}
func (UnimplementedCoursesServer) mustEmbedUnimplementedCoursesServer() {}

// UnsafeCoursesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoursesServer will
// result in compilation errors.
type UnsafeCoursesServer interface {
	mustEmbedUnimplementedCoursesServer()
}

func RegisterCoursesServer(s grpc.ServiceRegistrar, srv CoursesServer) {
	s.RegisterService(&Courses_ServiceDesc, srv)
}

func _Courses_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/Enroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_Unenroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnenrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).Unenroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/Unenroll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).Unenroll(ctx, req.(*UnenrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_GetEnrolledCoursesForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnrolledCoursesForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).GetEnrolledCoursesForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/GetEnrolledCoursesForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).GetEnrolledCoursesForUser(ctx, req.(*GetEnrolledCoursesForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/CreateCourse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).CreateCourse(ctx, req.(*CreateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_GetCourseToC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseToCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).GetCourseToC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/GetCourseToC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).GetCourseToC(ctx, req.(*GetCourseToCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_GetCourseSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).GetCourseSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/GetCourseSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).GetCourseSummary(ctx, req.(*GetCourseSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_GetCourseDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).GetCourseDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/GetCourseDashboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).GetCourseDashboard(ctx, req.(*GetCourseDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_GetAllPublicCourses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).GetAllPublicCourses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/GetAllPublicCourses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).GetAllPublicCourses(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/CreatePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courses_DeletePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoursesServer).DeletePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scholarlabs.services.course.Courses/DeletePage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoursesServer).DeletePage(ctx, req.(*DeletePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Courses_ServiceDesc is the grpc.ServiceDesc for Courses service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Courses_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scholarlabs.services.course.Courses",
	HandlerType: (*CoursesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _Courses_Enroll_Handler,
		},
		{
			MethodName: "Unenroll",
			Handler:    _Courses_Unenroll_Handler,
		},
		{
			MethodName: "GetEnrolledCoursesForUser",
			Handler:    _Courses_GetEnrolledCoursesForUser_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _Courses_CreateCourse_Handler,
		},
		{
			MethodName: "GetCourseToC",
			Handler:    _Courses_GetCourseToC_Handler,
		},
		{
			MethodName: "GetCourseSummary",
			Handler:    _Courses_GetCourseSummary_Handler,
		},
		{
			MethodName: "GetCourseDashboard",
			Handler:    _Courses_GetCourseDashboard_Handler,
		},
		{
			MethodName: "GetAllPublicCourses",
			Handler:    _Courses_GetAllPublicCourses_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _Courses_GetPage_Handler,
		},
		{
			MethodName: "CreatePage",
			Handler:    _Courses_CreatePage_Handler,
		},
		{
			MethodName: "DeletePage",
			Handler:    _Courses_DeletePage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/course.proto",
}
