CREATE TABLE IF NOT EXISTS environments (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    uuid VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL,

    owner_uuid VARCHAR(255) NOT NULL,
    prototype_uuid VARCHAR(255) NOT NULL,

    machine_uuid VARCHAR(255) UNIQUE NOT NULL,

    FOREIGN KEY (prototype_uuid) REFERENCES prototypes (uuid),
    FOREIGN KEY (owner_uuid) REFERENCES users (uuid),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)