apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  labels:
    component: gateway
spec:
  containers:
    - name: gateway
      image: foxfurry/scholarlabs-gateway
      envFrom:
        - configMapRef:
            name: scholarlabs-${ENVHASH}
      ports:
        - containerPort: 8000