apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: scholarlabs
spec:
  type: LoadBalancer
  #type: ClusterIP
  selector:
    component: gateway
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
status:
  loadBalancer: {}