apiVersion: v1
kind: Pod
metadata:
  name: gateway-pod
  namespace: scholarlabs
  labels:
    component: gateway
spec:
  containers:
    - name: gateway
      image: foxfurry/scholarlabs-gateway
      envFrom:
        - configMapRef:
            name: scholarlabs-gateway-${GATEWAYCONFIGHASH}
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
