apiVersion: v1
kind: Pod
metadata:
  name: user-pod
  labels:
    component: user
spec:
  containers:
    - name: user
      image: foxfurry/scholarlabs-user
      envFrom:
        - configMapRef:
            name: scholarlabs-user-${USERCONFIGHASH}
      imagePullPolicy: Always
      ports:
        - containerPort: 22000
