apiVersion: v1
kind: Service
metadata:
  name: environment-service
  namespace: scholarlabs
spec:
  type: ClusterIP
  selector:
    component: environment
  ports:
    - port: 22002
      targetPort: 22002
