CREATE TABLE IF NOT EXISTS courses (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    uuid VARCHAR(255) UNIQUE NOT NULL,
    author_uuid VARCHAR(255) NOT NULL,
    title VARCHAR(255) UNIQUE NOT NULL,
    short_description TEXT NOT NULL,
    description VARCHAR(255) NOT NULL,
    thumbnail TEXT NOT NULL,
    background TEXT,

    FOREIGN KEY (author_uuid) REFERENCES users (uuid),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)