CREATE TABLE IF NOT EXISTS enrolls (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    user_uuid VARCHAR(255) NOT NULL,
    course_uuid VARCHAR(255) NOT NULL,

    FOREIGN KEY (user_uuid) REFERENCES users (uuid),
    FOREIGN KEY (course_uuid) REFERENCES courses (uuid),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)