CREATE TABLE IF NOT EXISTS pages (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    page_id INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    course_uuid VARCHAR(255) NOT NULL,
    type enum('LESSON', 'ASSIGNMENT') NOT NULL,
    data blob NOT NULL,

    FOREIGN KEY (course_uuid) REFERENCES courses (uuid),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)